server:
  port: 8888
spring:
  application:
    name: config
  profiles:
    active: master
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mizhaoya2017/springcloud2.git #配置git仓库地址
          searchPaths: configDir/* #配置仓库路径
          username: mizhaoya2017 #访问git仓库的用户名
          password: mi18514812824 #访问git仓库的用户密码
      label: master #配置仓库的分支
  rabbitmq:
    host: 127.0.0.1
    port: 15672
    username: admin
    password: 123456
    virtualHost: /
    publisherConfirms: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info,bus-refresh
